'use client';

import { useState } from 'react';
import {
  X,
  Download,
  Share2,
  TrendingUp,
  TrendingDown,
  CircleAlert as AlertCircle,
  Target,
  Building2,
  Clock,
  ArrowUpRight,
  CircleCheck as CheckCircle2,
  FileText,
} from 'lucide-react';
import { useToast } from './toast';

interface StandupReportProps {
  open: boolean;
  onClose: () => void;
  onPostToSlack: () => void;
}

const RISK_DEALS = [
  {
    name: 'Acme Corp · Enterprise renewal',
    amount: '$185k',
    stage: 'Negotiation',
    risk: 'high',
    reason: 'Champion left last week. No new exec sponsor identified.',
    days: 14,
    rep: 'Sarah Chen',
    next: 'Schedule exec-to-exec call with new CTO by Thursday.',
  },
  {
    name: 'Globex Inc · Multi-year expansion',
    amount: '$160k',
    stage: 'Proposal',
    risk: 'high',
    reason: 'Procurement loop has stalled — 21 days without movement.',
    days: 21,
    rep: 'Marcus Rivera',
    next: 'Escalate to VP Sales · push for legal redlines this week.',
  },
  {
    name: 'Initech · Tier-up renewal',
    amount: '$100k',
    stage: 'Renewal',
    risk: 'medium',
    reason: 'Usage down 32% QoQ. CSM flagged churn signal.',
    days: 9,
    rep: 'Priya Shah',
    next: 'Trigger save-play: 90-day pilot extension + QBR with EVP.',
  },
];

const TOP_REPS = [
  { name: 'Sarah Chen', closed: '$420k', coverage: '4.2x', color: 'emerald' },
  { name: 'David Kim', closed: '$315k', coverage: '3.8x', color: 'emerald' },
  { name: 'Marcus Rivera', closed: '$280k', coverage: '2.1x', color: 'amber' },
];

const VELOCITY = [
  { stage: 'Discovery', count: 42, value: '$1.8M', delta: '+8%' },
  { stage: 'Demo', count: 24, value: '$1.4M', delta: '+12%' },
  { stage: 'Proposal', count: 12, value: '$760k', delta: '-4%' },
  { stage: 'Negotiation', count: 6, value: '$445k', delta: '+1%' },
];

export default function StandupReport({ open, onClose, onPostToSlack }: StandupReportProps) {
  const { push } = useToast();
  const [tab, setTab] = useState<'summary' | 'risks' | 'reps' | 'velocity'>('summary');

  if (!open) return null;

  const handleDownload = () => {
    const date = new Date().toISOString().split('T')[0];
    const content = `PIPELINE STANDUP — ${date}
================================================

Pipeline coverage: 3.4x (target 3.0x) ✅
Commit vs target: $4.2M / $5.0M (84%)
Deals at risk: 3 · $445k

DEALS AT RISK
${RISK_DEALS.map(
  (d) =>
    `- ${d.name}\n  ${d.amount} · ${d.stage} · ${d.days}d in stage · ${d.rep}\n  Risk: ${d.reason}\n  Next: ${d.next}`,
).join('\n\n')}

TOP REPS
${TOP_REPS.map((r) => `- ${r.name}: ${r.closed} closed · ${r.coverage} coverage`).join('\n')}

PIPELINE VELOCITY
${VELOCITY.map((v) => `- ${v.stage}: ${v.count} deals · ${v.value} (${v.delta} WoW)`).join('\n')}

Generated by Agentic Mobile · agentic.aurimas.io
`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `pipeline-standup-${date}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    push('success', 'Standup report downloaded');
  };

  const handleShare = async () => {
    const shareUrl = 'https://agentic.aurimas.io';
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Pipeline Standup Report',
          text: 'Pipeline coverage 3.4x · 3 deals at risk · $4.2M commit',
          url: shareUrl,
        });
        push('success', 'Report shared');
      } catch {
        /* user cancelled */
      }
    } else {
      await navigator.clipboard.writeText(shareUrl);
      push('success', 'Report link copied to clipboard');
    }
  };

  return (
    <div className="absolute inset-0 z-[85]">
      <div
        className="absolute inset-0 bg-slate-900/50 backdrop-blur-[2px] animate-fade-in"
        onClick={onClose}
      />

      <div className="absolute bottom-0 left-0 right-0 bg-[#FAF7F0] rounded-t-3xl h-[94%] overflow-hidden flex flex-col shadow-2xl shadow-slate-900/30 animate-slide-up">
        <div className="flex justify-center pt-2.5 pb-1">
          <div className="w-10 h-1 rounded-full bg-stone-300" />
        </div>

        {/* Header */}
        <div className="px-5 py-3 border-b border-stone-200">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-teal-50 flex items-center justify-center">
                <FileText className="w-4 h-4 text-teal-700" />
              </div>
              <div>
                <h2 className="text-sm font-semibold text-slate-900">Pipeline Standup</h2>
                <p className="text-[10px] text-slate-500">
                  {new Date().toLocaleDateString('en-US', {
                    weekday: 'long',
                    month: 'short',
                    day: 'numeric',
                  })}{' '}
                  · 12 reps · 84 deals
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-lg bg-stone-100 hover:bg-stone-200 flex items-center justify-center transition-colors active:scale-95"
            >
              <X className="w-4 h-4 text-slate-700" />
            </button>
          </div>

          {/* Tabs */}
          <div className="flex items-center gap-1.5 overflow-x-auto scrollbar-none">
            {(['summary', 'risks', 'reps', 'velocity'] as const).map((t) => (
              <button
                key={t}
                onClick={() => setTab(t)}
                className={`px-3 py-1.5 rounded-lg text-[11px] font-semibold whitespace-nowrap capitalize transition-colors ${
                  tab === t
                    ? 'bg-slate-900 text-white'
                    : 'bg-white border border-stone-200 text-slate-600 hover:text-slate-900'
                }`}
              >
                {t}
              </button>
            ))}
          </div>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-5 py-4 scrollbar-none">
          {tab === 'summary' && (
            <div className="space-y-3">
              {/* KPI cards */}
              <div className="grid grid-cols-2 gap-2.5">
                <div className="bg-white border border-stone-200 rounded-xl p-3">
                  <div className="flex items-center gap-1.5 mb-1">
                    <Target className="w-3.5 h-3.5 text-teal-700" />
                    <span className="text-[10px] uppercase tracking-wider text-slate-500 font-semibold">
                      Coverage
                    </span>
                  </div>
                  <p className="text-xl font-bold text-slate-900">3.4x</p>
                  <p className="text-[10px] text-emerald-700 font-medium">+0.4 vs last week</p>
                </div>
                <div className="bg-white border border-stone-200 rounded-xl p-3">
                  <div className="flex items-center gap-1.5 mb-1">
                    <TrendingUp className="w-3.5 h-3.5 text-emerald-700" />
                    <span className="text-[10px] uppercase tracking-wider text-slate-500 font-semibold">
                      Commit
                    </span>
                  </div>
                  <p className="text-xl font-bold text-slate-900">$4.2M</p>
                  <p className="text-[10px] text-slate-500 font-medium">84% of $5.0M target</p>
                </div>
                <div className="bg-white border border-stone-200 rounded-xl p-3">
                  <div className="flex items-center gap-1.5 mb-1">
                    <AlertCircle className="w-3.5 h-3.5 text-amber-700" />
                    <span className="text-[10px] uppercase tracking-wider text-slate-500 font-semibold">
                      At risk
                    </span>
                  </div>
                  <p className="text-xl font-bold text-slate-900">3 · $445k</p>
                  <p className="text-[10px] text-amber-700 font-medium">2 high · 1 medium</p>
                </div>
                <div className="bg-white border border-stone-200 rounded-xl p-3">
                  <div className="flex items-center gap-1.5 mb-1">
                    <Clock className="w-3.5 h-3.5 text-slate-700" />
                    <span className="text-[10px] uppercase tracking-wider text-slate-500 font-semibold">
                      Avg cycle
                    </span>
                  </div>
                  <p className="text-xl font-bold text-slate-900">42d</p>
                  <p className="text-[10px] text-emerald-700 font-medium">-3d vs last quarter</p>
                </div>
              </div>

              {/* Exec summary */}
              <div className="bg-white border border-stone-200 rounded-xl p-3.5 space-y-2">
                <div className="flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                  <span className="text-[10px] uppercase tracking-wider text-emerald-700 font-bold">
                    Executive summary
                  </span>
                </div>
                <p className="text-xs text-slate-700 leading-relaxed">
                  Pipeline is healthy at <span className="font-semibold">3.4x coverage</span>, up
                  from 3.0x last week, driven by strong top-of-funnel from the Q3 outbound
                  campaign. Commit confidence is solid at <span className="font-semibold">84%</span>.{' '}
                  <span className="font-semibold text-amber-700">
                    Three deals worth $445k need exec attention this week
                  </span>{' '}
                  — escalation paths recommended in the Risks tab.
                </p>
              </div>

              {/* Recommended actions */}
              <div className="bg-white border border-stone-200 rounded-xl p-3.5 space-y-2.5">
                <h3 className="text-xs font-bold text-slate-900 flex items-center gap-1.5">
                  <ArrowUpRight className="w-3.5 h-3.5 text-teal-700" />
                  Recommended actions today
                </h3>
                {[
                  'Acme Corp: 1:1 with new CTO before Thursday — Sarah needs intro from CRO',
                  'Globex: escalate procurement loop to legal — push redlines this week',
                  'Initech: trigger save-play — extend 90-day pilot + EVP-led QBR',
                  'Marcus Rivera: coverage at 2.1x — review pipeline gen plan in 1:1',
                ].map((action, i) => (
                  <div key={i} className="flex items-start gap-2">
                    <span className="text-[10px] font-bold text-teal-700 mt-0.5">{i + 1}.</span>
                    <p className="text-[11px] text-slate-700 leading-relaxed flex-1">{action}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {tab === 'risks' && (
            <div className="space-y-2.5">
              {RISK_DEALS.map((d, i) => (
                <div
                  key={i}
                  className={`bg-white border-l-4 ${
                    d.risk === 'high' ? 'border-l-rose-500' : 'border-l-amber-500'
                  } border-y border-r border-stone-200 rounded-xl p-3.5 space-y-2`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex-1 min-w-0">
                      <h3 className="text-xs font-semibold text-slate-900">{d.name}</h3>
                      <p className="text-[10px] text-slate-500 mt-0.5">
                        {d.stage} · {d.days}d in stage · {d.rep}
                      </p>
                    </div>
                    <span className="text-sm font-bold text-slate-900 whitespace-nowrap">
                      {d.amount}
                    </span>
                  </div>
                  <div className="bg-stone-50 rounded-lg p-2 space-y-1.5">
                    <div>
                      <p className="text-[9px] uppercase tracking-wider text-rose-700 font-bold">
                        Risk signal
                      </p>
                      <p className="text-[11px] text-slate-700 mt-0.5">{d.reason}</p>
                    </div>
                    <div>
                      <p className="text-[9px] uppercase tracking-wider text-emerald-700 font-bold">
                        Recommended next step
                      </p>
                      <p className="text-[11px] text-slate-700 mt-0.5">{d.next}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}

          {tab === 'reps' && (
            <div className="space-y-2">
              {TOP_REPS.map((r, i) => (
                <div
                  key={i}
                  className="bg-white border border-stone-200 rounded-xl p-3 flex items-center gap-3"
                >
                  <div className="w-9 h-9 rounded-full bg-gradient-to-br from-teal-100 to-stone-100 flex items-center justify-center text-xs font-bold text-teal-800">
                    {r.name
                      .split(' ')
                      .map((n) => n[0])
                      .join('')}
                  </div>
                  <div className="flex-1">
                    <p className="text-xs font-semibold text-slate-900">{r.name}</p>
                    <p className="text-[10px] text-slate-500">
                      {r.closed} closed · {r.coverage} coverage
                    </p>
                  </div>
                  <span
                    className={`text-[10px] font-bold px-2 py-1 rounded-md ${
                      r.color === 'emerald'
                        ? 'bg-emerald-100 text-emerald-700'
                        : 'bg-amber-100 text-amber-700'
                    }`}
                  >
                    {r.color === 'emerald' ? 'On track' : 'At risk'}
                  </span>
                </div>
              ))}
              <div className="bg-stone-100 rounded-xl p-3 text-center">
                <Building2 className="w-4 h-4 text-slate-500 mx-auto mb-1" />
                <p className="text-[10px] text-slate-600">9 more reps · view full leaderboard</p>
              </div>
            </div>
          )}

          {tab === 'velocity' && (
            <div className="space-y-2.5">
              <p className="text-[11px] text-slate-600">
                Deal flow by stage — week over week movement.
              </p>
              {VELOCITY.map((v, i) => {
                const max = Math.max(...VELOCITY.map((x) => x.count));
                const width = (v.count / max) * 100;
                const positive = v.delta.startsWith('+');
                return (
                  <div key={i} className="bg-white border border-stone-200 rounded-xl p-3 space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-semibold text-slate-900">{v.stage}</span>
                      <div className="flex items-center gap-2">
                        <span className="text-[11px] text-slate-500">{v.value}</span>
                        <span
                          className={`text-[10px] font-bold flex items-center gap-0.5 ${
                            positive ? 'text-emerald-700' : 'text-rose-700'
                          }`}
                        >
                          {positive ? (
                            <TrendingUp className="w-2.5 h-2.5" />
                          ) : (
                            <TrendingDown className="w-2.5 h-2.5" />
                          )}
                          {v.delta}
                        </span>
                      </div>
                    </div>
                    <div className="h-2 bg-stone-100 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-teal-600 rounded-full transition-all duration-500"
                        style={{ width: `${width}%` }}
                      />
                    </div>
                    <p className="text-[10px] text-slate-500">{v.count} deals</p>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Footer actions */}
        <div className="px-5 py-3 border-t border-stone-200 bg-white grid grid-cols-3 gap-2">
          <button
            onClick={handleDownload}
            className="flex items-center justify-center gap-1.5 py-2.5 rounded-lg bg-stone-100 hover:bg-stone-200 text-slate-700 text-xs font-semibold transition-colors active:scale-95"
          >
            <Download className="w-3.5 h-3.5" /> Download
          </button>
          <button
            onClick={handleShare}
            className="flex items-center justify-center gap-1.5 py-2.5 rounded-lg bg-stone-100 hover:bg-stone-200 text-slate-700 text-xs font-semibold transition-colors active:scale-95"
          >
            <Share2 className="w-3.5 h-3.5" /> Share
          </button>
          <button
            onClick={() => {
              onClose();
              onPostToSlack();
            }}
            className="flex items-center justify-center gap-1.5 py-2.5 rounded-lg bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold transition-colors active:scale-95"
          >
            Post to Slack
          </button>
        </div>
      </div>
    </div>
  );
}
